# Generated by Django 4.2 on 2023-04-20 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_secao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=255)),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.secao')),
            ],
        ),
    ]
