# Generated by Django 4.2.2 on 2023-06-15 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='preco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_secao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='media')),
                ('status', models.CharField(default='1', max_length=2, null=True)),
                ('carousel', models.CharField(default='0', max_length=2)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
                ('preco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.preco')),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.secao', verbose_name='Seção')),
            ],
        ),
    ]
