# Generated by Django 4.2.1 on 2023-05-30 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='preco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_secao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, upload_to='produto/media')),
                ('empresa', models.ForeignKey(default='Informe o estabelecimento', null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
                ('preco', models.ForeignKey(default='Informe a Preço', null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.preco')),
                ('secao', models.ForeignKey(default='Informe a Seção', on_delete=django.db.models.deletion.CASCADE, to='produto.secao', verbose_name='Seção')),
            ],
        ),
    ]
