# Generated by Django 4.2 on 2023-04-21 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='produto/media'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='secao',
            field=models.ForeignKey(default='Informe a Seção', on_delete=django.db.models.deletion.CASCADE, to='produto.secao', verbose_name='Seção'),
        ),
    ]
