# Generated by Django 4.2 on 2023-04-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produtos_imagem_alter_produtos_secao'),
    ]

    operations = [
        migrations.CreateModel(
            name='preco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
            ],
        ),
    ]
