# Generated by Django 4.2 on 2023-05-08 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_alter_empresa_quant_prod'),
        ('produto', '0004_produtos_preco_alter_preco_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preco',
            field=models.ForeignKey(default='Informe a Preço', null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.preco'),
        ),
    ]
