# Generated by Django 4.2 on 2023-05-08 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_alter_empresa_quant_prod'),
        ('produto', '0005_alter_produtos_empresa_alter_produtos_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='empresa',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa'),
        ),
    ]
