# Generated by Django 4.2 on 2023-06-13 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_empresa_pacote'),
        ('produto', '0009_alter_produtos_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='carousel',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='produtos',
            name='status',
            field=models.CharField(default='1', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.preco'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='secao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.secao', verbose_name='Seção'),
        ),
    ]
