# Generated by Django 4.2 on 2023-07-04 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_produtos_carousel_produtos_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_busca', models.DateField(default=None)),
                ('produto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='produto.produtos')),
            ],
        ),
    ]
