# Generated by Django 4.2.2 on 2023-06-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Pacote')),
                ('custo', models.CharField(max_length=10, verbose_name='Custo do Pacote')),
                ('quant_prod', models.IntegerField(verbose_name='Quantidade de Produtos')),
                ('quant_carousel', models.IntegerField(default=0, verbose_name='Quantidade de itens de Carousel')),
                ('descricao', models.TextField(verbose_name='Descrição do Pacote')),
                ('img', models.ImageField(default='media/sem_foto.png', upload_to='pacotes/media', verbose_name='Animação do Pacote(.gif)')),
            ],
        ),
    ]
