# Generated by Django 4.2 on 2023-06-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacote',
            name='descricao',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
