# Generated by Django 4.2 on 2023-06-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacotes', '0002_pacote_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacote',
            name='custo',
            field=models.FloatField(verbose_name='Custo do Pacote'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='descricao',
            field=models.TextField(verbose_name='Descrição do Pacote'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Pacote'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='quant_prod',
            field=models.IntegerField(verbose_name='Quantidade de Produtos'),
        ),
    ]
