# Generated by Django 4.2 on 2023-06-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacotes', '0003_alter_pacote_custo_alter_pacote_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacote',
            name='img',
            field=models.ImageField(default='media/sem_foto.png', upload_to='pacotes/media', verbose_name='Animação do Pacote(.gif)'),
        ),
    ]
