# Generated by Django 4.2 on 2023-06-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacotes', '0005_alter_pacote_custo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacote',
            name='quant_carousel',
            field=models.IntegerField(default=0, verbose_name='Quantidade de itens de Carousel'),
        ),
    ]
