# Generated by Django 4.2 on 2023-05-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_empresa_quant_prod_alter_empresa_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='quant_prod',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
