# Generated by Django 4.2 on 2023-05-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_alter_empresa_quant_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
