# Generated by Django 4.2 on 2023-06-09 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_empresa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.cidade'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.tipos'),
        ),
    ]
