# Generated by Django 4.2 on 2023-06-09 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacotes', '0003_alter_pacote_custo_alter_pacote_descricao_and_more'),
        ('empresa', '0005_alter_empresa_cidade_alter_empresa_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='pacote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pacotes.pacote', verbose_name='Selecione o Pacote'),
        ),
    ]
