# Generated by Django 4.2 on 2023-07-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_empresa_pacote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='quant_prod',
            field=models.IntegerField(default=0),
        ),
    ]
